### ISSUE TITLE
directly injected component is rendered in outer-root if custom root is set

### ISSUE THREAD

**Issue by ShiiRochi** [ShiiRochi/react-callable#6]
Hot it should work?
If customRoot is set and directInjection is enabled, proxy callable is rendered in outer-root and component are rendered in customRoot

How it is working?
If customRoot is set and directInjection is enabled, proxy callable and component are rendered inside outer-root

**Comment by john-dominguez** [comment]
I'm unable to use the custom root, as it only creates an empty div in it.
